# Generated by Django 4.2 on 2025-07-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='short_description',
            field=models.TextField(default='default.jpg', max_length=500),
            preserve_default=False,
        ),
    ]
